"""
Purpose:
    Seed the running simulator with the sample campaigns and creatives
    from seed_data.json, using the real HTTP API (Features 1 and 2).

Responsibilities:
    - POST each campaign; remember its server-generated id by name
    - POST each creative, translating its campaign_name into that id
      (ids are generated by the server, so seed data cannot know them
      in advance -- names are the stable reference)
    - Print a summary; fail with a clear message if the server is down

Dependencies:
    - json, urllib, pathlib (standard library only)

Usage:
    python app.py            (in one terminal)
    python samples/seed.py   (in another)

Note: seeding twice creates duplicates (the API has no upsert -- creation
only, per the brief). For a clean slate, reset each file in data/ to []
first, or run samples/run_tests.py which resets automatically.
"""

import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

BASE_URL = "http://localhost:5000"
SEED_FILE = Path(__file__).resolve().parent / "seed_data.json"


def post(path: str, body: dict) -> dict:
    """POST a JSON body to the API and return the parsed JSON reply."""
    request = urllib.request.Request(
        BASE_URL + path,
        data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request) as response:
        return json.loads(response.read())


def main() -> None:
    seed = json.loads(SEED_FILE.read_text(encoding="utf-8"))
    try:
        campaign_ids_by_name = {}
        for campaign in seed["campaigns"]:
            created = post("/api/campaigns", campaign)
            campaign_ids_by_name[created["name"]] = created["id"]
            print(f"campaign  {created['id']}  {created['name']}"
                  f"  ({created['status']}, {created['cpm_bid']} CPM)")

        for creative in seed["creatives"]:
            body = dict(creative)
            body["campaign_id"] = campaign_ids_by_name[body.pop("campaign_name")]
            created = post("/api/creatives", body)
            print(f"creative  {created['id']}  {created['name']}"
                  f"  ->  {created['campaign_id']}")

        print("\nSeed complete. Open http://localhost:5000/ to see the dashboard,")
        print("then try:  curl -X POST http://localhost:5000/openrtb/bid "
              '-H "Content-Type: application/json" -d @samples/bid_request_match.json')
    # HTTPError is a subclass of URLError, so it must be caught FIRST --
    # the other order would swallow API errors into "server unreachable".
    except urllib.error.HTTPError as error:
        print(error.read().decode())
        raise
    except urllib.error.URLError:
        sys.exit("Could not reach the server. Start it first:  python app.py")


if __name__ == "__main__":
    main()
